"""Hardware detection package — CPU, memory, NUMA, IO, interconnect detection."""

from .detection import SysFSHardwareInfo
from .types import (
    HardwareInfoProvider,
    parse_cpu_list,
    parse_memory_string,
)
from .wrapper import (
    calculate_peak_fp64_gflops,
    check_elpa_available,
    check_mkl_available,
    get_cache_topology,
    get_cpu_architecture,
    get_cpu_frequency_info,
    get_cpu_generation,
    get_cpu_governor,
    get_fma_units_per_core,
    get_hardware_profile,
    get_interconnect_info,
    get_job_memory_limit_mb,
    get_logical_cores,
    get_memory_bandwidth_gb_s,
    get_numa_node_count,
    get_numa_topology_detailed,
    get_physical_cores,
    get_provider,
    get_scratch_filesystem_type,
    get_system_type,
    get_total_mem_kb,
    get_vector_isa_and_width,
    is_containerized,
    is_hyperthreading_active,
    set_provider,
)

__all__ = [
    "HardwareInfoProvider",
    "SysFSHardwareInfo",
    "calculate_peak_fp64_gflops",
    "check_elpa_available",
    "check_mkl_available",
    "get_cache_topology",
    "get_cpu_architecture",
    "get_cpu_frequency_info",
    "get_cpu_generation",
    "get_cpu_governor",
    "get_fma_units_per_core",
    "get_hardware_profile",
    "get_interconnect_info",
    "get_job_memory_limit_mb",
    "get_logical_cores",
    "get_memory_bandwidth_gb_s",
    "get_numa_node_count",
    "get_numa_topology_detailed",
    "get_physical_cores",
    "get_provider",
    "get_scratch_filesystem_type",
    "get_system_type",
    "get_total_mem_kb",
    "get_vector_isa_and_width",
    "is_containerized",
    "is_hyperthreading_active",
    "parse_cpu_list",
    "parse_memory_string",
    "set_provider",
]
