from __future__ import annotations

import argparse
from typing import Any

from rich.table import Table

from ..config import AppConfig
from ._utils import get_console
from .base import register_command


def register(subparsers: argparse._SubParsersAction) -> None:
    p = subparsers.add_parser("workflow", help="Generate workflow YAML templates")
    p.add_argument("action", type=str, choices=["create", "list", "visualize"], help="Workflow action")
    p.add_argument("--case", type=str, default="case", help="Case name")
    p.add_argument("--steps", type=str, default="scf,dos,band", help="Comma-separated workflow steps")
    p.add_argument("--output", type=str, default=None, help="Output YAML path")


def handle(args: argparse.Namespace, cfg: AppConfig) -> dict[str, Any]:
    console = get_console()
    steps = [s.strip() for s in args.steps.split(",")]

    if args.action == "list":
        tasks = []
        prev = None
        for i, step in enumerate(steps):
            node_id = f"{args.case}_{step}"
            tasks.append((step, str(i + 1), prev if prev else "-"))
            prev = node_id

        table = Table(title=f"Workflow: {args.case}", border_style="cyan")
        table.add_column("Step", style="bold")
        table.add_column("Order")
        table.add_column("Depends On")
        for task in tasks:
            table.add_row(*task)
        console.print(table)
        return {"status": "listed", "steps": steps}

    yaml_content = f"# WIEN2k workflow generated by forge\ncase: {args.case}\nsteps: [{', '.join(steps)}]\nscheduler: auto\nauto_retry: true\nmax_retries: 3\npoll_interval: 5.0\n"
    output = args.output or f"{args.case}_workflow.yaml"
    with open(output, "w", encoding="utf-8") as f:
        f.write(yaml_content)

    console.print(f"[green]Workflow template saved to {output}[/green]")
    console.print(f"  Steps: {', '.join(steps)}")
    return {"status": "created", "output": output, "steps": steps}


register_command("workflow", handle)
